### ISSUE TITLE
Can't find the example map

### ISSUE THREAD

**Issue by JaegeunJung** [BlueVoidStudios/EdUtilExamples#2]
When I open the project, there are no examples at all.
Everytime I open the project, it says "Failed to load the map!".
Any ideas?

**Comment by JaegeunJung** [comment]
Download as Zip file was the problem. (don't know why)
When I clone the repository and open the project, it works.

**Comment by pfist** [comment]
Thanks for reporting this. I'll look into why this is happening and, if I can reproduce the issue, I'll work on a fix.

**Comment by klixoft** [comment]
Had the same issues cloning works otherwise it breaks

**Comment by SirVoxelot** [comment]
downloading the zip wouldn't open the project for me
but cloning it with github desktop seemed to work
and changing the project to 2.45 works, thanks for the learning files!

something about a git LFS, i guess it doesn't look for those large files when it's a zip download

**Comment by pfist** [comment]
Thanks for the reports, folks. This was due to an issue with the Download ZIP button not downloading LFS-managed files. 

I published [a new release](https://github.com/BlueVoidStudios/EdUtilExamples/releases) with a working ZIP to download. Moving forward, that'll be the place to download releases if you don't want to clone the repo.
